### ISSUE TITLE
[열차추가] ICE1, 2, 3, 3(407), [수정] ICE4

### ISSUE THREAD

**Issue by Gamunbi** [MEGB-NewGRF/EuropeanTrainSet#10]
==========[필수스프라이트]==========
![유럽열차세트 ICE 1차완성](https://user-images.githubusercontent.com/75788864/185953676-caccc727-6758-4cfd-b11c-bb3951b1e153.png)
![유럽열차세트 ICE 1차완성 초록](https://user-images.githubusercontent.com/75788864/185953680-18142f1c-e9ed-4005-9382-cc649bc2930d.png)
초록색 버전

==========[설명]==========
한꺼번에 많이 만들었기 때문에, 스프라이트 오류가 있을 수 있습니다.. 

ICE4도 약간 수정되었습니다. 게임에서 볼 때 큰 차이 없는 수준입니다.

모든 스프라이트가 같은 크기입니다.

==========[YST적용내용]==========
|GRF내 열차 이름| ICE1| ICE2|ICE3|ICE3 407| ICE4|
|-|-|-|-|-|-|
|열차속도|310km/h|310km/h|330km/h|330km/h|265km/h|
|도입년도|1989|1995|2000|2010|2017|
|객차당 수송량|객차마다 다름|"|"|"|"|

**Comment by GBLINER** [comment]
![ICE](https://user-images.githubusercontent.com/85421764/186059058-e5cb9a26-c4de-4749-917b-2ae6a1b94569.png)

후미등 추가 및 일부 개선된 스프라이트로 적용할 예정.
ICE 1 그린도색 삭제 (실존하지 않음)

**Comment by Gamunbi** [comment]
![0001](https://user-images.githubusercontent.com/75788864/186095723-a3a5ebd2-9f57-4b54-aa68-e24c44b37444.png)
수정한 버전

![0002](https://user-images.githubusercontent.com/75788864/186095727-04076755-9822-468a-ad42-ded40f6bffe7.png)
수정한 버전 (초록)

![0003](https://user-images.githubusercontent.com/75788864/186095732-813b4c15-f1e6-4893-a3e3-d1eebb0ebacf.png)
ICE3 파랑
